[package]
name = "rsa"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
hex = "0.4.3"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
sha1 = "0.10.6"
